application: beehive
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /musiclocker
  mime_type: text/plain
  static_dir: mirror/

- url: /templates
  mime_type: text/plain
  static_dir: templates/

- url: /testdata
  mime_type: text/plain
  static_dir: testdata/

- url: /manifest
  mime_type: text/plain
  static_files: static/manifest.txt
  upload: static/manifest\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static\favicon\.ico

- url: /(COPYING|README\.md|SHA256\.sig|app\.yaml)$
  mime_type: text/plain
  static_files: \1
  upload: (COPYING|README\.md|SHA256\.sig|app\.yaml)$

- url: /(tunes|v1/.*)$
  script: _go_app
