application: beehive
version: 1
runtime: go
api_version: go1

handlers:
- url: /(COPYING|COPYING\.APL|README\.md|SHA256\.sig)$
  mime_type: text/plain
  static_files: \1
  upload: (COPYING|COPYING\.APL|README\.md|SHA256\.sig)$

- url: /favicon\.ico$
  static_files: static/favicon.ico
  upload: static/favicon\.ico$

- url: /musiclocker
  mime_type: text/plain
  static_dir: mirror/musiclocker

- url: /robots\.txt$
  static_files: static/robots.txt
  upload: static/robots\.txt$

- url: /static
  static_dir: mirror/static

- url: /templates
  mime_type: text/plain
  static_dir: mirror/templates

- url: /testdata
  static_dir: mirror/testdata

- url: /(tunes|v1/.*)$
  script: _go_app
